development:
  adapter: postgis
  database: spinmap_development
  host: localhost
  username: spinmap
  password: 
  su_username: adam
  su_password: 
  postgis_extension: ['postgis', 'hstore']

test:
  adapter: postgis
  database: spinmap_test
  host: localhost
  username: spinmap
  password: 
  su_username: adam
  su_password: 
  postgis_extension: true

production:
  adapter: postgresql
  encoding: unicode
  database: spinmap_production
  pool: 5
  username: spinmap
  password:
