development: &base
  adapter: postgis
  database: whospins_development
  host: localhost
  username: spinmap
  password: 
  su_username: adam
  su_password: 
  postgis_extension: ['postgis', 'hstore']

test:
  database: whospins_test
  <<: *base

production:
  database: whospins_production
  <<: *base