defaults: &base
  adapter: postgis
  host: localhost  
  pool: 20
  postgis_extension: ['postgis', 'hstore']

development: 
  <<: *base
  database: whospins_development
  username: spinmap
  password: 
  su_username: adam
  su_password: 


test:
  <<: *base
  database: whospins_test


production:
  <<: *base
  database: whospins_production
  host: db1.whospins.com
  username: whospins
  su_username: postgres
