development:
  adapter: postgresql
  encoding: unicode
  database: spinmap_development
  pool: 5
  username: spinmap
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: spinmap_test
  pool: 5
  username: spinmap
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: spinmap_production
  pool: 5
  username: spinmap
  password:
