defaults: &base
  adapter: postgis
  host: localhost
  username: whospins
  su_username: postgres 
  pool: 20
  postgis_extension: ['postgis', 'hstore']

development: 
  <<: *base
  database: whospins_development

test:
  <<: *base
  database: whospins_test


production:
  <<: *base
  database: whospins_production
  host: db1.whospins.com
